sudo: false
dist: trusty
language: node_js
node_js:
- '8'
- '10'
os:
- linux
cache:
  directories:
  - bower_components
  - "$HOME/.npm"
  - "$(npm config get prefix)"
before_install:
- npm install -g codecov bower
install:
- npm install
- bower install
after_success: npm run report-coverage
jobs:
  include:
  - stage: "NPM Release @next"
    if: type = push # add master later
    script: skip
    deploy:
    - provider: npm
      tag: next
      email:
        secure: VAevo66XIzgA9mbhQhnouv101W7HVhHGvohxmJtGadGL/kwVuMZcYp5nG3IwuetYDpjCmRTY0My13HRBG7ciVg7CW+Wx/raLmST09QokEtvIcvLwGBmxBjR37UnU/SD65XjgAqM+sNPoCTe6vxaJVoInR8uNxdi6IsYiOE9wlmE=
      api_key:
        secure: MwR9W8ositdbBKRVg+oV7vUK43Gcs8eCZNSJejVAAk+rLZuwkpr9DPR6I5Crh6/8IblHD87xI90DPN5BGf0BJRzwVxeJWCuLaOwO5eUmqlXSrJt3VAoGDkxYzh2nm92CLnek6PxdeoZwqap2wDKUBoPh+Je7uZucgtRU27x7sUc=
      skip_cleanup: true
      on:
        all_branches: true
  - stage: "GitHub Release"
    if: type = push AND tag IS present
    script: skip
    before_deploy:
    - mv $(npm pack 2>/dev/null) "nodecg-${TRAVIS_TAG}.tgz"
    deploy:
    - provider: releases
      api_key:
        secure: ph/2keCTbmoaCIFhBZE65Tj1DcRHf3U+Dk3KSVZOOR29NbI3tkwpoLjl0OQpeLtHqgu76L/W+B1ZFGQbegjHRCYOz6bvzLxe37c0p0FNmt+rWnyHAtri9O4iPObgsGX7t2+A2Qehq0NgM6KkjSQRRYpfF+Vx1S5+grTXY/lm/cI=
      file: "nodecg-${TRAVIS_TAG}.tgz"
      skip_cleanup: true
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8c1769bff63cbd033bf7
    on_success: always
    on_failure: always
    on_start: never
  slack:
    secure: R+TkavWRhREwc9shV6JYJ+YrrMdpaSB5iYlVVhtO4XjSJPtbsgFvg8aelELIfwUY/Lsl6dmUD8bhv1GxN4Bdui7igrGEzXqh+ziJSnPET0Apxyc2HFYzM3phQYwsESyFXGfx9PiegLQ6fcozZ75rio17YhPjT8//9jb5I9hue9g=
