# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.11"
    - nodejs_version: "0.12"
    - nodejs_version: "iojs"

# Allow failing jobs for bleeding-edge Node.js versions.
matrix:
  fast_finish: true
  allow_failures:
    - nodejs_version: "0.11"
    - nodejs_version: "0.12"
    - nodejs_version: "iojs"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Install dependencies
  - npm install

# Post-install test scripts.
test_script:
  - cmd: npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"

# Slack alerts for failures
notifications:
  - provider: Slack
    auth_token:
      secure: nwMVzoe5QgwKrCU1WpPVg645UjOZ4g8xdTan41DSVd0I2M6wcYoCwavNa2umEoyh
    channel: github
    on_build_success: false
    on_build_failure: true
