name: CI

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable pnpm
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint

  test-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable pnpm
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm typetest

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable pnpm
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Ensure that bundle git parsing functionality works
        run: |
          git config --global user.email "ci@nodecg.dev"
          git config --global user.name "NodeCG Bot"

      - name: Restore Puppeteer cache (Linux)
        if: runner.os == 'Linux'
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.cache/puppeteer
          key: puppeteer-${{ runner.os }}

      - name: Restore Puppeteer cache (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\.cache\puppeteer
          key: puppeteer-${{ runner.os }}

      - run: pnpm install
      - run: pnpm exec puppeteer browsers install chrome
      - run: pnpm build

      - run: pnpm exec vitest --coverage --reporter=default --reporter=junit --outputFile=test-report.junit.xml
      - if: success() || failure()
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: test-report.junit.xml
          flags: ${{ runner.os }}
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  container-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "runs in merge queue"

  pr-release:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: pr-release
    needs:
      - lint
      - test-types
      - build-test
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable pnpm
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: pnpm install
      - run: pnpm build

      - run: |
          NEW_VERSION="0.0.0-pr${{ github.event.number }}.${{ github.sha }}"
          pnpm -r exec pnpm version "$NEW_VERSION" --no-git-tag-version
          pnpm version "$NEW_VERSION" --no-git-tag-version

          pnpm -r publish --tag pr${{ github.event.number }} --no-git-checks
          pnpm publish --tag pr${{ github.event.number }} --no-git-checks
          pnpm exec tsx scripts/prepare-publish-types.ts
          pnpm publish --tag pr${{ github.event.number }} --no-git-checks

      - name: Comment PR with install instructions
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.number }} --body "PR release is published and can be installed as \`nodecg@pr${{ github.event.number }}\`"

  release-please:
    permissions:
      contents: write
      pull-requests: write
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    outputs:
      pr: ${{ steps.release.outputs.pr }}
      releases_created: ${{ steps.release.outputs.releases_created }}
      release_paths: ${{ steps.release.outputs.paths_released }}
      root_release_created: ${{ steps.release.outputs.release_created }}
      root_release_version: ${{ steps.release.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json

  update-release-pr:
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.pr }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.NODECG_MONOREPO_GH_TOKEN }}
      - run: gh pr checkout ${{ fromJson(needs.release-please.outputs.pr).number }}
        env:
          GH_TOKEN: ${{ secrets.NODECG_MONOREPO_GH_TOKEN }}
      - run: corepack enable pnpm
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - run: |
          git config --global user.email "ci@nodecg.dev"
          git config --global user.name "NodeCG"
      - run: |
          pnpm install
          if git diff --quiet pnpm-lock.yaml; then
            git commit -m "chore: run CI" --allow-empty
            git push
          else
            git add pnpm-lock.yaml
            git commit -m "chore: update pnpm-lock.yaml"
            git push
          fi

  publish:
    permissions:
      contents: read
      id-token: write
    needs:
      - release-please
      - lint
      - test-types
      - build-test
    environment: ${{ needs.release-please.outputs.releases_created == 'true' && 'latest-release' || 'canary-release' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: corepack enable pnpm
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - run: pnpm install
      - run: pnpm build

      - if: ${{ needs.release-please.outputs.releases_created == 'true' }}
        name: Publish to NPM
        run: |
          echo '${{ needs.release-please.outputs.release_paths }}' | jq -r '.[]' | while read -r path; do
            if [[ "$path" == "." ]]; then
              pnpm publish --tag latest
              pnpm exec tsx scripts/prepare-publish-types.ts
              pnpm publish --tag latest
            else
              (cd "$path" && pnpm publish --tag latest)
            fi
          done

      - if: ${{ needs.release-please.outputs.releases_created != 'true' }}
        name: Publish Canary to NPM
        run: |
          NEW_VERSION="0.0.0-canary.${{ github.sha }}"
          pnpm -r exec pnpm version "$NEW_VERSION" --no-git-tag-version
          pnpm version "$NEW_VERSION" --no-git-tag-version

          pnpm -r publish --tag canary --no-git-checks
          pnpm publish --tag canary --no-git-checks
          pnpm exec tsx scripts/prepare-publish-types.ts
          pnpm publish --tag canary --no-git-checks

  docker-image:
    permissions:
      contents: write
      packages: write
    needs:
      - release-please
      - lint
      - test-types
      - build-test
    if: ${{ needs.release-please.outputs.root_release_created == 'true' }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ needs.release-please.outputs.root_release_version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.release-please.outputs.root_release_version }}
            type=semver,pattern={{major}},value=${{ needs.release-please.outputs.root_release_version }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
